runtime: python310
entrypoint: gunicorn -b :$PORT paultolrem.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: 'paultolrem.settings'

beta_settings:
  cloud_sql_instances: glass-stratum-383701:europe-west1:instanciaperronalav00z=tcp:3306

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 5

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
